#!/bin/bash
# TRnews 完整自动化流程
# 确保每次定时器启动能完成所有链条

set -e

WORKSPACE="/home/sai/.openclaw/workspace-selfmng"
TRENDRADAR_DIR="$WORKSPACE/workspace/TrendRadar"
NEWS_DIR="$WORKSPACE/skills/outputs/daily-news"
NEWS_SCRIPT_DIR="$WORKSPACE/skills/news-social-workflow"
TRNEWS_DIR="$WORKSPACE/TRnews"
LOG_DIR="$WORKSPACE/memory/news-workflow"

DATE=$(date +%Y-%m-%d)
TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)

# 确保日志目录存在
mkdir -p "$LOG_DIR"
mkdir -p "$TRNEWS_DIR"

echo "=========================================="
echo "🚀 TRnews 完整自动化流程"
echo "📅 日期：$DATE"
echo "⏰ 时间：$TIMESTAMP"
echo "==========================================" | tee -a "$TRNEWS_DIR/complete-cron.log"

# 阶段 1: 运行 TrendRadar
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 阶段 1: TrendRadar 抓取"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
cd "$WORKSPACE"
bash "$NEWS_SCRIPT_DIR/orchestrator.sh" --force-ai 2>&1 | tee -a "$WORKSPACE/memory/news-workflow/cron.log"

# 阶段 2: 检查 AI 分析
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🤖 阶段 2: 检查 AI 分析"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
AI_FILE="$NEWS_DIR/ai-analysis-$DATE.md"
if [ -f "$AI_FILE" ]; then
    SECTIONS=$(grep "^## " "$AI_FILE" | wc -l)
    echo "✅ AI 分析提取成功：$SECTIONS 个板块"
else
    echo "❌ AI 分析文件不存在"
    exit 1
fi

# 阶段 3: 生成所有平台稿件
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 阶段 3: 生成所有平台稿件"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
cd "$NEWS_SCRIPT_DIR"

# 清理旧文件，确保生成最新内容
rm -f "$NEWS_DIR"/2026-*.md "$NEWS_DIR"/2026-*.txt 2>/dev/null || true
rm -f "$NEWS_DIR"/ai-analysis-*.md "$NEWS_DIR"/news-*.json 2>/dev/null || true

# 使用 v1 脚本生成所有平台稿件
python3 generate-news-from-ai.py

# 检查生成的文件
PLATFORMS=("wechat" "weibo" "twitter" "zhihu" "xiaohongshu" "toutiao")
echo ""
echo "生成的文件："
for platform in "${PLATFORMS[@]}"; do
    FILE="$NEWS_DIR/$DATE-$platform.md"
    if [ -f "$FILE" ]; then
        LINES=$(wc -l < "$FILE")
        echo "  ✅ $platform: $LINES 行"
    else
        echo "  ❌ $platform: 未生成"
    fi
done

# 阶段 4: 复制到 TRnews
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📂 阶段 4: 复制到 TRnews"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
cd "$TRNEWS_DIR"

# 创建目录
mkdir -p "data/$DATE/trendradar-html"
mkdir -p "reports/$DATE"
mkdir -p "platforms/xiaohongshu/$DATE"
mkdir -p "platforms/toutiao/$DATE"
mkdir -p "platforms/wechat/$DATE"
mkdir -p "platforms/weibo/$DATE"
mkdir -p "platforms/twitter/$DATE"
mkdir -p "platforms/zhihu/$DATE"

# 复制数据文件
cp "$NEWS_DIR/ai-analysis-$DATE.md" "data/$DATE/" 2>/dev/null && echo "✅ 复制 AI 分析" || echo "⚠️ AI 分析未找到"
cp "$NEWS_DIR/news-$DATE.json" "data/$DATE/" 2>/dev/null && echo "✅ 复制新闻数据" || echo "⚠️ 新闻数据未找到"
cp "$TRENDRADAR_DIR/output/html/$DATE"/*.html "data/$DATE/trendradar-html/" 2>/dev/null && echo "✅ 复制 HTML 报告" || echo "⚠️ HTML 报告未找到"

# 复制新闻报告
cp "$NEWS_DIR/$DATE-"*.md "reports/$DATE/" 2>/dev/null && echo "✅ 复制新闻报告" || echo "⚠️ 新闻报告未找到"

# 复制平台稿件
for platform in "${PLATFORMS[@]}"; do
    SRC="$NEWS_DIR/$DATE-$platform.md"
    DST="platforms/$platform/$DATE/"
    DST_TXT="platforms/$platform/$DATE/"
    if [ -f "$SRC" ]; then
        cp "$SRC" "$DST" 2>/dev/null && echo "✅ 复制 $platform 稿件" || echo "❌ 复制 $platform 失败"
        cp "${SRC%.md}.txt" "$DST_TXT" 2>/dev/null || true
    fi
done

# 创建综合摘要
echo ""
echo "创建综合摘要..."
cat > "reports/$DATE/summary.md" << EOF
# $DATE 新闻报告综合摘要

## 📊 数据概览

| 项目 | 数值 |
|------|------|
| 监测平台 | 11 个 |
| AI 分析板块 | 5 个 |
| 生成稿件 | $(ls reports/$DATE/*.md 2>/dev/null | wc -l) 篇 |

## 📱 发布内容

EOF

for platform in "${PLATFORMS[@]}"; do
    FILE="platforms/$platform/$DATE/$DATE-$platform.md"
    if [ -f "$FILE" ]; then
        LINES=$(wc -l < "$FILE")
        echo "- **$platform**: $LINES 行" >> "reports/$DATE/summary.md"
    fi
done

cat >> "reports/$DATE/summary.md" << EOF

## 📂 文件位置

\`\`\`
data/$DATE/
├── ai-analysis-$DATE.md
├── news-$DATE.json
└── trendradar-html/

reports/$DATE/
├── $DATE-wechat.md
├── $DATE-weibo.md
├── $DATE-twitter.md
├── $DATE-zhihu.md
└── summary.md

platforms/
├── xiaohongshu/$DATE/
├── toutiao/$DATE/
├── wechat/$DATE/
├── weibo/$DATE/
├── twitter/$DATE/
└── zhihu/$DATE/
\`\`\`

---

*Generated by TrendRadar AI | $DATE*
EOF
echo "✅ 创建综合摘要"

# 阶段 5: Git 提交和推送
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💾 阶段 5: Git 提交和推送"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# 检查是否有新文件
NEW_FILES=$(git status --porcelain | wc -l)
if [ $NEW_FILES -eq 0 ]; then
    echo "⚠️  没有新文件，跳过推送"
else
    echo "📥 拉取远程仓库..."
    git pull origin main 2>/dev/null || echo "首次推送，跳过拉取"
    
    echo "➕ 添加文件到 Git..."
    git add .
    
    echo "💾 Git 提交..."
    git commit -m "📰 $DATE 新闻报告更新" || echo "无变更"
    
    echo "🚀 推送到 GitHub..."
    git push origin main
    
    echo ""
    echo "✅ 推送完成！"
    echo "🔗 https://github.com/SamuelPang/TRnews"
fi

echo ""
echo "=========================================="
echo "✅ 完整流程完成！"
echo "📅 日期：$DATE"
echo "⏰ 耗时：$(($(date +%s) - ${START_TIME:-$(date +%s)})) 秒"
echo "=========================================="
