#!/bin/bash
# TRnews 每日发布脚本

set -e

# 配置
WORKSPACE="/home/sai/.openclaw/workspace-selfmng"
TRENDRADAR_DIR="$WORKSPACE/workspace/TrendRadar"
NEWS_DIR="$WORKSPACE/skills/news-social-workflow"
TRNEWS_DIR="$WORKSPACE/TRnews"

DATE=$(date +%Y-%m-%d)
TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)

echo "=========================================="
echo "📰 TRnews 每日发布脚本"
echo "📅 日期：$DATE"
echo "=========================================="

# 1. 运行 TrendRadar
echo ""
echo "🚀 步骤 1: 运行 TrendRadar..."
cd "$WORKSPACE"
bash skills/news-social-workflow/orchestrator.sh --force-ai

# 2. 复制数据文件
echo ""
echo "📋 步骤 2: 复制数据文件..."
mkdir -p "$TRNEWS_DIR/data/$DATE/trendradar-html"
cp "$TRENDRADAR_DIR/output/html/$DATE"/*.html "$TRNEWS_DIR/data/$DATE/trendradar-html/" 2>/dev/null || true
cp "$NEWS_DIR/outputs/daily-news/ai-analysis-$DATE.md" "$TRNEWS_DIR/data/$DATE/" 2>/dev/null || true
cp "$NEWS_DIR/outputs/daily-news/news-$DATE.json" "$TRNEWS_DIR/data/$DATE/" 2>/dev/null || true

# 3. 复制新闻报告
echo ""
echo "📝 步骤 3: 复制新闻报告..."
mkdir -p "$TRNEWS_DIR/reports/$DATE"
cp "$NEWS_DIR/outputs/daily-news/$DATE-"*.md "$TRNEWS_DIR/reports/$DATE/" 2>/dev/null || true

# 4. 复制平台稿件
echo ""
echo "📱 步骤 4: 复制平台稿件..."
mkdir -p "$TRNEWS_DIR/platforms/xiaohongshu/$DATE"
mkdir -p "$TRNEWS_DIR/platforms/toutiao/$DATE"
cp "$NEWS_DIR/outputs/daily-news/$DATE-xiaohongshu.md" "$TRNEWS_DIR/platforms/xiaohongshu/$DATE/" 2>/dev/null || true
cp "$NEWS_DIR/outputs/daily-news/$DATE-toutiao.md" "$TRNEWS_DIR/platforms/toutiao/$DATE/" 2>/dev/null || true

# 5. 创建综合摘要
echo ""
echo "📊 步骤 5: 创建综合摘要..."
cat > "$TRNEWS_DIR/reports/$DATE/summary.md" << EOF
# $DATE 新闻报告综合摘要

## 📊 数据概览

| 项目 | 数值 |
|------|------|
| 监测平台 | 11 个 |
| AI 分析板块 | 5 个 |
| 生成稿件 | 待统计 |

## 📂 文件位置

\`\`\`
data/$DATE/
├── ai-analysis.md
├── news-data.json
└── trendradar-html/

reports/$DATE/
├── wechat.md
├── weibo.md
└── summary.md

platforms/
├── xiaohongshu/$DATE/
└── toutiao/$DATE/
\`\`\`

---

*Generated by TrendRadar AI | $DATE*
EOF

# 6. 更新月度索引
echo ""
echo "📅 步骤 6: 更新月度索引..."
MONTH=$(date +%Y-%m)
mkdir -p "$TRNEWS_DIR/archive/$MONTH"

cat >> "$TRNEWS_DIR/archive/$MONTH/index.md" << EOF

### $DATE

**文件位置：**
- 数据：\`data/$DATE/\`
- 报告：\`reports/$DATE/\`
- 稿件：\`platforms/*/$DATE/\`

---
EOF

# 7. Git 提交
echo ""
echo "💾 步骤 7: Git 提交..."
cd "$TRNEWS_DIR"
git add .
git commit -m "📰 $DATE 新闻报告更新" || echo "No changes to commit"

echo ""
echo "=========================================="
echo "✅ 发布完成！"
echo "📂 文件位置：$TRNEWS_DIR"
echo "=========================================="
